### PR TITLE
Use Alpine Linux

### PR DESCRIPTION
**Pull request by matthewvalimaki**
Use Alpine Linux, drop the dependencies from `Dockerfile`. Not quite sure what those were used in the first place.

### CODE REVIEW

**Comment by tleyden** [comment]
Thanks for the contribution!

**Comment by tleyden** [comment]
It's rebuilding on dockerhub .. I'll keep an eye on it.

https://hub.docker.com/r/tleyden5iwx/couchbase-cluster-go/

**Comment by matthewvalimaki** [comment]
@tleyden awesome! Thanks! :+1:

**Comment by tleyden** [comment]
Np!  Btw you can find me on gitter in the https://gitter.im/couchbase/discuss channel.

**Comment by tleyden** [comment]
The docker build finished.  Ditto for the etcd-discovery image https://hub.docker.com/r/tleyden5iwx/etcd-discovery

**Pull request merged**
